name: Deploy mdBook to GH Pages

on:
  push:
    branches:
      - "master"

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
    steps:
      - uses: actions/checkout@v4.1.1

      - name: Setup mdBook
        uses: peaceiris/actions-mdbook@v2.0.0
        with:
          mdbook-version: "0.5.4"
      - run: mdbook build

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v4.0.0
        if: ${{ github.ref == 'refs/heads/master' }}
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./book/html
          publish_branch: html
          cname: f-14-manual.ttsandbox.click

      - name: Discord Notification
        if: success()
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
        run: |
          if [ -n "$DISCORD_WEBHOOK" ]; then
            curl -H "Content-Type: application/json" \
                 -X POST \
                 -d '{"content": "🚀 **New Update!** The F-14 Manual has just been successfully built and deployed! Check it out here: https://f-14-manual.ttsandbox.click"}' \
                 $DISCORD_WEBHOOK
          else
            echo "Discord Webhook secret is not set. Skipping notification."
          fi
