name: Build and Deploy mdBook PDF

on:
  push:
    tags:
      - "*"

permissions:
  contents: write

jobs:
  deploy-pdf:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.1.1

      - name: Setup mdBook
        uses: peaceiris/actions-mdbook@v2.0.0
        with:
          mdbook-version: "0.5.4"
      - run: cargo install mdbook-pdf --version 0.1.13 --locked
      - run: mdbook build

      - name: Rename PDF
        run: mv book/pdf/output.pdf book/pdf/f14_manual.pdf

      - name: Release PDF
        uses: ncipollo/release-action@v1.14.0
        with:
          artifactErrorsFailBuild: true
          artifacts: "book/pdf/f14_manual.pdf"
          artifactContentType: "application/pdf"
          generateReleaseNotes: true
          omitBody: true
          omitName: true

      - name: Discord Notification
        if: success()
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
        run: |
          if [ -n "$DISCORD_WEBHOOK" ]; then
            curl -H "Content-Type: application/json" \
                 -X POST \
                 -d '{"content": "📄 **New PDF Release!** A new version of the F-14 Manual PDF is now available for download: https://github.com/${{ github.repository }}/releases/tag/${{ github.ref_name }}"}' \
                 $DISCORD_WEBHOOK
          else
            echo "Discord Webhook secret is not set. Skipping notification."
          fi
